config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'pages#home'

  resources :posts
  resource :session

  scope :diary, controller: :diary do
    get '/' => :index, as: :diary
    get '/:date' => :show, as: :diary_entry, constraints: { date: /20\d\d-(0[1-9]|1[012])-(0[1-9]|[12]\d|3[01])/ }
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/controllers/diary_controller.rb
# frozen_string_literal: true

# Public diary controller
class DiaryController < ApplicationController
  allow_unauthenticated_access

  # get /diary
  def index
    @collection = DiaryService.list(current_page)
  end

  # get /diary/:date
  def show
    @date = Date.parse(params[:date].to_s)
    @adjacent = DiaryService.adjacent_dates(@date)
    @collection = Post.where(date: @date).list
  end
end

app/helpers/diary_helper.rb
# frozen_string_literal: true

module DiaryHelper
  # @param [Post|Date] entity
  # @param [String] text
  # @param [Hash] options
  def diary_entry_link(entity, text = entity.title_for_page, options = {})
    date = entity.is_a?(Post) ? entity.date : entity
    link_to(text, diary_entry_path(date: date.strftime('%F')), options)
  end

  # Entry title with sibling name and post title, if present
  #
  # @param [Post] entity
  def diary_entry_title(entity)
    if entity.title.blank?
      entity.sibling.name
    else
      "#{entity.sibling.name}: #{entity.title}"
    end
  end
end

app/views/diary/_date.html.erb
<section class="diary">
  <hgroup>
    <h2><%= diary_entry_link(date, l(date)) %></h2>
    <p><%= l(date, format: '%A') %></p>
  </hgroup>
  <% posts.each do |entity| %>
    <%= render partial: 'diary/entry_preview', locals: { entity: } %>
  <% end %>
</section>

app/views/diary/_entity.html.erb
<article class="post">
  <hgroup>
    <h2><%= diary_entry_title(entity) %></h2>
  </hgroup>

  <% if entity.image.attached? %>
    <figure>
      <div class="image">
        <%= post_image_large(entity) %>
      </div>
    </figure>
  <% end %>

  <div class="post-body">
    <%= simple_format(entity.body_for_page) %>
  </div>
</article>

app/views/diary/_entry_preview.html.erb
<article class="post-preview">
  <hgroup>
    <h3><%= diary_entry_link(entity, diary_entry_title(entity)) %></h3>
  </hgroup>

  <figure>
    <div class="image">
      <% if entity.image.attached? %>
        <%= post_image_small(entity) %>
      <% else %>
        <%= image_tag('posts/placeholder.svg', alt: '') %>
      <% end %>
    </div>
  </figure>

  <div class="post-body">
    <%= simple_format(entity.preview) %>
    <p><%= diary_entry_link(entity, entity.read_more_text) %> &hellip;</p>
  </div>
</article>

app/views/diary/index.html.erb
<% content_for :title, t('.title', page: current_page) %>
<% content_for :breadcrumbs do %>
  <span><%= t('.nav_text') %></span>
<% end %>

<section>
  <h1><%= t('.heading') %></h1>

  <%= paginate @collection[:dates] %>
  <% @collection[:posts].each do |date, posts| %>
    <%= render partial: 'diary/date', locals: { date:, posts: } %>
  <% end %>
  <%= paginate @collection[:dates] %>
</section>

app/views/diary/show.html.erb
<% content_for :title, t('.title', date: params[:date]) %>
<% content_for :breadcrumbs do %>
  <%= link_to(t('diary.index.nav_text'), diary_path) %>
  <span><%= l(@date) %></span>
<% end %>

<section class="diary">
  <hgroup>
    <h1><%= t('.heading', date: l(@date)) %></h1>
    <p><%= l(@date, format: '%A') %></p>
  </hgroup>

  <nav class="adjacent">
    <% if @adjacent[:prev].present? %>
      <%= diary_entry_link(@adjacent[:prev], l(@adjacent[:prev]), class: 'prev') %>
    <% end %>
    <% if @adjacent[:next].present? %>
      <%= diary_entry_link(@adjacent[:next], l(@adjacent[:next]), class: 'next') %>
    <% end %>
  </nav>

  <% @collection.each do |entity| %>
    <%= render partial: 'diary/entity', locals: { entity: } %>
  <% end %>
</section>